#
# description: Archivo que contiene variables de entorno
# author: William Cauich
# creationDate: 12 de Enero del 2022
#
service: example-tsc-serverless
frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  region: us-east-1
  stage: dev
  environment: ${file(env.yml):${self:custom.stage}}
  logRetentionInDays: ${self:custom.environment.LOG_RETENTION_IN_DAYS}

  ### VPC par conectarse a RDS ###
  vpc:
    securityGroupIds:
      - ${self:custom.secrets.SECURITY_GROUP_ID}

    subnetIds:
      - ${self:custom.secrets.SUBNET1_ID}
      - ${self:custom.secrets.SUBNET2_ID}
      - ${self:custom.secrets.SUBNET3_ID}
      - ${self:custom.secrets.SUBNET4_ID}
  ###

# Lambda functions
functions:
  # Archivo de configuración
  '${file(all.api.serverless.yml)}'

# Plugins de Serverless
plugins:
  - serverless-plugin-typescript
  - serverless-offline
  - serverless-plugin-split-stacks
  - serverless-prune-plugin

# Variables custom para serverless
custom:
  # Archivo de secrets
  secrets: ${file(secrets.json)}
  # Etapa de proyecto
  stage: '${opt:stage, self:provider.stage}'
  # Obtiene las variables del archivo env.yml
  environment: ${file(custom-env.yml):${self:custom.stage}, file(custom-env.yml):default}
  # Configuración de plugin serverless split stack
  splitStacks:
    # nestedStackCount: 4 # Controls the number of created nested stacks
    perFunction: false
    perType: true
    perGroupFunction: false
  # Purga las versiones de la lambda para retener solo las últimas tres
  prune:
    automatic: true
    number: 2